sudo: false
language: python
dist: focal
matrix:
  fast_finish: true
  include:
    - python: '3.8'
      env: TOXENV=py38
    - python: '3.9'
      env: TOXENV=py39
    - python: '3.9'
      env: TOXENV=black
    - python: '3.9'
      env: TOXENV=flake8
install:
  - pip install -U tox coveralls poetry
script:
  - tox
cache: pip
after_success:
  - coveralls
deploy:
  provider: script
  script: poetry publish --build -u __token__ -p $POETRY_PYPI_TOKEN_PYPI -vvv
  on:
    tags: true
    branch: main
    repo: markallanson/octopus-energy
    python: '3.8'
  skip_existing: true
env:
  global:
    secure: l9fzsnHL4PkxofsiEmFoHMMQvcw3Z+4H87qXKsKYvdTLMMkACJMRmlfaj9nXgJUmvjc7A30cjBhKtIyeqLDIrvh5QgQsCVJBmGS5+l5BYZ7pbNl/y+L5PMMdcu39/HOgLZQuCfYLMujGNP39WrTx+D4iw8U2wYJBEkjkjCIvKmLJtzGTGCeiXXJOm62pMXFOPKmwIAhY3obOEz3j8KDbtuctIBTEus1dryIlD1lOL16t7CFfeHrt//fX5nyzWDaYUkBd+u647bBkmvVznzrsk1qrn6VvjwxVIcpZsRaoXYMi6mmATvPviug8QZIi0BAUgRfcJanJmqtwcGZXApWSke8Y/Z5YAqSXe+U1mN/tXpzXFSnX4NkFtAdV8wAVz8ndXoxRFvvXdUlnnl8chL8zbAvg/3KzHQdP9kSj4T56xfBQqHGfp+9JPhTBaAbZ0QVz9VaEtTUw/0X/ztzq55w+yUJRmvwsSI6PgBiCaVGnLIPSUak7MZl8so6kFV7OE0+uwSLaeJUSejFKvIkSHbgeeMIJnFv55swgL63CS7Z4aHMp/kmgDQFZsBlasMAIAdy6IEFxqALgSGD7XOnHM/RpJoo7fZ+uo0HxS035vk6KB6J+dz/ay2JswjlWiolPShqlCAz9mcH/dW9kIvRBLlMiUXW38stdyx5MxQki/DntR0c=
